spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xrDB
    username: root
    password:
  jpa :
    hibernate.ddl-autp: update
    generate-ddl: true
    show-sql: true
