spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xrDB
    username: root
    password:
  jpa :
    generate-ddl: true
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          wr
